version: '2'

volumes:
  fcrepo:
  solr:
  db:
  redis:
  app:

networks:
   internal:

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=development
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      internal:

  redis:
    image: redis:3
    command: redis-server
    volumes:
      - redis:/data
    expose:
      - 6379
    networks:
      internal:
    ports:
      - 6379:6379

  app:
    image: ualibraries/hyku_app
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://postgres@db/development
      - SETTINGS__ACTIVE_JOB__QUEUE_ADAPTER=sidekiq
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=asdf
    volumes:
      - solr:/solr
      - fcrepo:/fedora
    networks:
      internal:

  web:
    extends: app
    command: /usr/local/bin/start_hyku.sh
    expose:
      - 3000
    depends_on:
      - db
      - redis
    volumes:
      - app:/data/public/uploads
    ports:
      - 3000:3000
      - 8983:8983
      - 8984:8984

  setup:
    extends: app
    environment:
      - RDS_DB_NAME=development
      - RDS_USERNAME=postgres
      - RDS_PASSWORD=''
      - RDS_HOSTNAME=db
      - RDS_PORT=5432
    command: /bin/bash -c "if [ ! -e /db/initialized ]; then sleep 25 && /data/bin/setup && touch /db/initialized; fi"
    volumes:
      - db:/db
    depends_on:
      - db
      - web

