version: '2.1'

volumes:
  fedora:
  solr:
  db:
  redis:
  app:

services:

# this is postgress database image
  db:
    image: postgres
    healthcheck:
      test: pg_isready -h localhost -p 5432 -q -U postgres
      interval: 5s
      timeout: 5s
      retries: 100

    volumes:
      - db:/var/lib/postgresql/data

# REDIS in memory database
  redis:
    image: redis:3
    command: redis-server
    volumes:
      - redis:/data
#    ports:
#      - 6379:6379
#
# SOLR indexing
  solr:
    image: ualibraries/solr_hydra
    command: /usr/local/bin/start_solr.sh
    environment:
      - SOLR_CORE=production
    volumes:
      - solr:/opt/solr/server/solr
#    ports:
#      - 8983:8983

# Fedora object store
  fedora:
    image: ualibraries/fedora
    volumes:
      - fedora:/fedora
#    ports:
#      - 8080:8080

# This image actually runs hyku app
  web:
    image: ualibraries/hyku_app
    command: /usr/local/bin/start_hyku.sh
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - SETTINGS__ACTIVE_JOB__QUEUE_ADAPTER=sidekiq
      - FEDORA_URL=http://fedora:8080/fcrepo/rest
      - SOLR_URL=http://solr:8983/solr/hydra-production
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${HOSTPORT}:3000
    volumes:
      - app:/data/public/uploads
